### ISSUE TITLE
add link to spec work / any differences?

### ISSUE THREAD

**Issue by daKmoR** [AdobeXD/design-system-package-dsp#1]
I think it would be nice to show the relationship to the spec work?

so maybe add links to twitter @DesignTokens
and/or to the repo https://github.com/design-tokens/community-group.
and/or to the w3c community: https://w3.org/community/design-tokens/

also maybe nice to highlight what might be different here?

**Comment by demianborba** [comment]
Great suggestion @daKmoR . As an update, we are waiting for the decision/draft that's being done on the tokens spec, to then evaluate how we could incorporate the recommendation to DSP. And we are in conversations with the community group.

**Comment by Pickachu** [comment]
Any updates on this?
