### ISSUE TITLE
Clarifications about design-dev handoff using DSP

### ISSUE THREAD

**Issue by johnjacobkenny** [AdobeXD/design-system-package-dsp#11]
I love the strides Adobe and the community are making in order to have a seamless design-dev experience and I'm excited to be working as a developer in these times. :partying_face: 

I am coming from a UI dev background and have a few doubts on my mind about a few of the common workflows and how it would look like going forward. I am looking to work with the UI team in my company to use DSP to build out our design system. I have gone through a few resources available on the https://letsxd.com/vscode website as well as on youtube, but did not get conclusive answers. I understand that this is very early in the DSP, but I'm assuming that many of these concerns have been thought through, and will come in a future update to the spec or the vs code plugin. :smiley: 

I am documenting these questions as well as my assumptions. I hope that someone from Adobe or DSP core group could share their feedback on it. :heart: 

### 1. After the initial creation of the DSP, how will we incorporate any updates that are happening on XD?
As per the resources available I can see that we can import the design tokens directly from an XD library which has been shared using a web link. This can be used to create the DSP package. Once the package is created, we can make changes to the package and change just about anything here. But I am assuming that the most obvious changes may be to add documentation regarding the tokens and also adding code snippets for the same.

But once that is done, and there is an update from the design side, how can we incorporate those updates back into the DSP? Perhaps there may be an option to fetch updates from the public XD library, which will pull down the changes and allow the developer to review them and create the new version of the DSP.

Update: In the XD plugin for VS Code, there is a DSP Settings option. There at the bottom there is an option to import the tokens again. This import step essentially pulls down all the latest changes made to the library. But it is not clear whether any newly added tokens are overwritten, etc.

### 2. After creating and adding developer documentation in the DSP, can it be synced back to XD?
I have not worked on XD, but is there any way that any of the changes added to the DSP can be synced back to XD so that both are equally the single source of truth.

### 3. How does a UI component development tool like storybook fit into the picture?
The DSP generates CSS, JS etc. containing the tokens required to build the design system components (say, in React). So I am assuming that storybook would still be relevant in terms of providing the place for the developer to run and test the components (especially edge cases) in isolation rather that having a clunky workflow by building a proper react app. 

But what about the documentation features of storybook and of DSP? I can see the value that the DSP adds for the developer within the IDE (auto complete snippets, documentation), and I can see the value add of having the storybook accessible for anyone in the org for reference. In other words, should the final documentation reside on storybook, or on the DSP or on both? is there a way to keep them in sync to get the best of both worlds?

### 4. How can we keep multiple design systems in sync
Typically we would have an organization wide design system, and multiple application level design systems which inherit most of the tokens and components from the parent, while adding/overriding a few tokens or components as required for the application. As per the inputs from my design team, they would create a library for the master design system, and then whatever changes are required for the application design system - only those changes would be made available in the library for the application design system. **Is this an expected practice?**

If that is the way to go, then is there any way to merge the master DSP with the application DSP so that we are able to load just the application DSP on VS Code and we will get access to all the tokens, etc. I am seeing three options here,

a. The designer needs to manage the tokens and figure out how to keep in sync using XD
b. The developer needs to figure out how to merge the two DSPs
c. Adobe figures out a way to update the plugin to incorporate these

### Additional questions
5. Do we create separate (say npm) packages for the DSP and for our design system library?
6. Are there any ideas on how to version the library on XD and on DSP side?
7. Is there any way that when there is an XD update, the DSP can be auto updated using some build pipeline?
8. Is there an option to import multiple XD libraries (say separate libraries for each components) using the VS Code plugin?

Thanks for taking time to go through these. :heart:

**Comment by demianborba** [comment]
Thanks for all the detailed questions @johnjacobkenny. Really appreciate the time invested in DSP and in the extension for VS Code.

Answers below:

1. You are right, design changes can be imported on subsequent imports via DSP Settings. Only design changes will be overwritten, preserving your additions to elements in DSP such as documentation, tags, or code snippets.
- Colors and character styles will have their names and values updated.
- Components will have their names and renditions updated.
Everything else added to your DSP will be preserved.

2. Changes to DSP are not syncing back to XD. It's a one time pull from the CC Library to VS Code (DSP). If we identify a big demand for a more connected scenario, we will evaluate the idea of updates going in both ways. It'll be great if everything is always in sync.

3. In the documentation portion of your DSP elements, you can use markdown with basic HTML, including iframes. That means you can expose the coded component coming from Storybook in DSPs using iframes. The code snippet is not connected to code sources, but we saw some teams generating DSPs programmatically, always pulling from code sources (e.g. Knapsack: http://knapsack.cloud/dsp) And we are also talking with the Storybook team on an addon to export DSPs.

4. DSPs are defined by a core dsp.json file that can import other JSONs such as components, tokens etc. You could use the import mechanism to import from other DSPs.

5. Some companies are creating smaller DSPs per color theme or platform. It is up to each team to define how big/complete each DSP will be.

6. Libraries will go through the regular versioning design cycle (assets.adobe.com). For DSPs, we recommend tracking changes with git.

7. We are discussing a new feature to automatically inform the DSP creator that a design update was made, via Webhooks.

8. You can technically import multiple libraries, but there is no UI to manage multiple links yet.

Hope it helps. And feel free to ping me on Twitter (@demianborba) if you want to schedule a time to speak in more detail.

**Comment by johnjacobkenny** [comment]
@demianborba thanks for the detailed response! I will get back to you for further queries 🙂
