### ISSUE TITLE
Can't import CC Library including components

### ISSUE THREAD

**Issue by tlosbar** [AdobeXD/design-system-package-dsp#13]
It seems to have an issue with CC Library which has components.

I correctly Authenticate my Adobe Account.
I can import a CC Library which has only typography or color assets. But when I try to import one with components I get this error message: **Sorry! There was an issue trying to import your CC Library, go back and try again**.

**Comment by demianborba** [comment]
Thank you for filing an issue @tlosbar. Could you please share the library link you're trying to import?

**Comment by tlosbar** [comment]
A few days later, I was able to import my library without knowing what might have changed. Maybe I deleted symbols inherited from other libraries. 
Thank you. I close this issue
