### ISSUE TITLE
Clarify "alias" token value

### ISSUE THREAD

**Issue by CITguy** [AdobeXD/design-system-package-dsp#8]
Does the value of an Alias Token reference the `id` or the `name` of another token?

The examples aren't clear, because the `cta-background` alias in the example uses `"{primary-red}"`, which is both the `id` _and_ the `name` of the referenced Token entity.

**Comment by demianborba** [comment]
Thanks for the question @CITguy. The extension looks for the name, and if it can't find it, it will look for the ID.
