### ISSUE TITLE
Does snippet/code completion support tab completions

### ISSUE THREAD

**Issue by warrenbuckley** [AdobeXD/design-system-package-dsp#9]
Hi 👋 
Just come across this DSP spec from Adobe Max 2020 & the VSCode extension page - https://letsxd.com/vscode

Does this spec support tab completions in the inserted snippets.
For example with the bootstrap example shown, it would be good to tab through the inserted snippet for the component to say quickly update the title/header of a card and any other useful things.

Is this something that can be done already or would this be something worth exploring if it currently does not support it.

Thanks,
Warren :)

**Comment by demianborba** [comment]
Hi Warren, yes, you can use tab stops just like any other snippet in VS Code.

![image](https://user-images.githubusercontent.com/2474382/100294496-ce8f3600-2f3b-11eb-8964-f000a172ef1a.png)

https://code.visualstudio.com/docs/editor/userdefinedsnippets
![image](https://user-images.githubusercontent.com/2474382/100294581-0c8c5a00-2f3c-11eb-8391-a1d42398db24.png)
